id: 'living_room_lights_off_2300'
alias: Turn Off Living Room Ceiling Lights at 11 PM
description: "Turn off LR Back Left Ceiling, LR Front Right Ceiling, and LR Back Right Ceiling every night at 11:00 PM"
mode: single
trigger:
  - platform: time
    at: '23:00:00'
conditions: []
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.hue_lr_back_left_ceiling
        - light.hue_color_downlight_1_4
        - light.hue_color_downlight_1