id: 'living_room_lights_off_2300'
alias: Turn Off Living Room Lights at 11 PM
description: "Turn off the Living Room Light every night at 11:00 PM"
mode: single
trigger:
  - platform: time
    at: '23:00:00'
conditions: []
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.living_room_2
        - light.hue_lr_back_left_ceiling
        - light.hue_color_downlight_1_4
        - light.hue_color_downlight_1_3
        - light.hue_play_1