id: 'after_sunset_living_room_office_wled_sequence'
alias: After Sunset Living Room and Office WLED Sequence
description: "After sunset every day, turn on the Living Room light for 5 minutes, then turn on the Office WLED, wait 30 seconds, and finally turn off the Living Room light."
mode: single
trigger:
  - platform: sun
    event: sunset
conditions: []
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room_2
  - delay: '00:05:00'
  - service: light.turn_on
    target:
      entity_id: light.wled
  - delay: '00:00:30'
  - service: light.turn_off
    target:
      entity_id: light.living_room_2