id: 'living_room_light_off_2300'
alias: Turn Off LR Front Right Ceiling at 11 PM
description: "Turn off the LR Front Right Ceiling light every night at 11:00 PM."
mode: single
trigger:
  - platform: time
    at: '23:00:00'
conditions: []
action:
  - service: light.turn_off
    target:
      entity_id: light.hue_color_downlight_1_4