id: 'living_room_evening_dim_40'
alias: Living Room - Dim Ceiling Lights After 8 PM
description: "When Living Room ceiling lights are turned on after 20:00, dim them to ~40% brightness"
mode: single
trigger:
  - platform: state
    entity_id:
      - light.hue_lr_back_left_ceiling
      - light.hue_color_downlight_1
      - light.hue_color_downlight_1_4
    from: 'off'
    to: 'on'
conditions:
  - condition: time
    after: '20:00:00'
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.hue_lr_back_left_ceiling
        - light.hue_color_downlight_1
        - light.hue_color_downlight_1_4
    data:
      brightness: 100