id: 'living_room_lights_dim_after_8pm'
alias: Living Room Lights - Dim to 40 Percent After 8 PM
description: "When LR ceiling lights turn on after 8 PM - dim to 40% brightness"
mode: single
trigger:
  - platform: state
    entity_id:
      - light.hue_color_downlight_1_4
      - light.hue_color_downlight_1
    from: 'off'
    to: 'on'
conditions:
  - condition: time
    after: '20:00:00'
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.hue_color_downlight_1_4
        - light.hue_color_downlight_1
    data:
      brightness_pct: 40