id: 'living_room_lights_auto_dim_after_8pm'
alias: Living Room Lights Auto Dim After 8 PM
description: "When Living Room ceiling lights are turned on after 8:00 PM, dim to 40% brightness."
mode: single
trigger:
  - platform: state
    entity_id:
      - light.hue_color_downlight_1
      - light.hue_color_downlight_1_4
      - light.hue_lr_back_left_ceiling
    from: 'off'
    to: 'on'
conditions:
  - condition: time
    after: '20:00:00'
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.hue_color_downlight_1
        - light.hue_color_downlight_1_4
        - light.hue_lr_back_left_ceiling
    data:
      brightness_pct: 40