id: 'living_room_wled_notifier_21_23'
alias: Living Room Evening Office WLED Pulse
description: "When the Living Room light is turned on between 9:00 PM and 11:00 PM, briefly turn on the Office WLED at 20% brightness for 10 seconds, then turn it back off."
mode: single
trigger:
  - platform: state
    entity_id: light.living_room_2
    to: 'on'
conditions:
  - condition: time
    after: '21:00:00'
    before: '23:00:00'
action:
  - service: light.turn_on
    target:
      entity_id: light.wled
    data:
      brightness_pct: 20
  - delay: '00:00:10'
  - service: light.turn_off
    target:
      entity_id: light.wled