id: 'after_sunset_living_room_then_office_wled'
alias: After Sunset - Living Room then Office WLED
description: "After sunset turn on Living Room for 5 minutes, then Office WLED for 30 seconds, then turn off Living Room"
mode: single
trigger:
  - platform: sun
    event: sunset
conditions: []
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room_2
  - delay: '00:05:00'
  - service: light.turn_on
    target:
      entity_id: light.wled
  - delay: '00:00:30'
  - service: light.turn_off
    target:
      entity_id: light.living_room_2