id: 'lr_evening_lights_1800'
alias: Living Room Ceiling Lights 6PM On
description: "Between 6:00 PM and 11:00 PM every day, set the Living Room ceiling lights to 80% brightness at 6 PM"
mode: single
trigger:
  - platform: time
    at: '18:00:00'
conditions:
  - condition: time
    before: '23:00:00'
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.hue_lr_back_left_ceiling
        - light.hue_color_downlight_1_4
        - light.hue_color_downlight_1
    data:
      brightness_pct: 80