id: 'living_room_pulse_office_wled_21_23'
alias: Living Room Evening Pulse Office WLED
description: "When the Living Room light is turned on between 9:00 PM and 11:00 PM, pulse the Office WLED to 20% brightness for 10 seconds then turn it off."
mode: single
trigger:
  - platform: state
    entity_id: light.living_room_2
    from: 'off'
    to: 'on'
conditions:
  - condition: time
    after: '21:00:00'
    before: '23:00:00'
action:
  - service: light.turn_on
    target:
      entity_id: light.wled
    data:
      brightness_pct: 20
  - delay: '00:00:10'
  - service: light.turn_off
    target:
      entity_id: light.wled