id: 'turn_off_living_room_lights_2300'
alias: Turn Off Living Room Lights at 11 PM
description: "Turn off all Living Room ceiling lights every night at 11:00 PM"
mode: single
trigger:
  - platform: time
    at: '23:00:00'
conditions: []
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.hue_color_downlight_1_4
        - light.hue_color_downlight_1
        - light.hue_lr_back_left_ceiling