id: 'living_room_6pm_11pm'
alias: Living Room Evening Schedule
description: "Between 6 PM and 11 PM every day, turn Living Room light on at 80% and off at 11 PM"
mode: single
trigger:
  - platform: time
    at: '18:00:00'
  - platform: time
    at: '23:00:00'
conditions: []
action:
  - choose:
      - conditions:
          - condition: time
            after: '17:59:59'
            before: '18:00:01'
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.living_room_2
            data:
              brightness_pct: 80
      - conditions:
          - condition: time
            after: '22:59:59'
            before: '23:00:01'
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.living_room_2