id: 'living_room_evening_lights_80_brightness'
alias: Living Room Evening Lights 80% Brightness
description: "Between 6:00 PM and 11:00 PM, set LR Back Right and LR Front Right Ceiling to 80% brightness"
mode: single
trigger:
  - platform: time
    at: '18:00:00'
conditions:
  - condition: time
    after: '18:00:00'
    before: '23:00:00'
action:
  - service: light.turn_on
    target:
      entity_id:
        - light.hue_color_downlight_1
        - light.hue_color_downlight_1_4
    data:
      brightness: 204